UTILS_C = utils.c
UTILS_H = utils.h
CC = clang
CFLAGS = -Wall -Wextra

# $@ is the target name
# $< is the first prerequisite

q01: q01.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)

q02: q02.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)

q03: q03.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)

q04: q04.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)

q05: q05.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)

q06: q06.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)

q08: q08.c $(UTILS_C) $(UTILS_H)
	$(CC) $(CFLAGS) -o $@.o $< $(UTILS_C)
